Add Hadolint and Trivy Checks
zeitgeistpm/zeitgeist pull request #557
Opened 2022-04-11 11:06 UTC by samuelarogbonlo

2022-04-13 18:52 UTC, sea212 reviewed
This is just a fast scan-over opinion, proper review coming soon.

The major thing I see is that we do the checks when we want to publish the docker images. I assume an lint/security issue will stop the publishing of the image, won't it?
I think it would be better to check those before a PR is merged into main. In regards to that, it would be nice to triggers those checks only when relevant changes are made.

2023-02-10 15:54 UTC, samuelarogbonlo commented
Hello @sea212 can you please take a look at the changes I've made so far? And possibly take a look at the results of the job in https://github.com/zeitgeistpm/zeitgeist/actions/runs/4145477882/jobs/7169887429

2023-08-03 09:47 UTC, sea212 approved these changes

2023-08-03 09:50 UTC, sea212 requested changes

2023-08-03 09:50 UTC, sea212 commented on .github/workflows/docker-hub.yml
> +    branches: [ main ]
```suggestion
```

2023-08-03 09:51 UTC, sea212 approved these changes

2023-08-03 09:52 UTC, merged