[WIP] Implements scalar markets
zeitgeistpm/zeitgeist pull request #76
Opened 2021-04-15 11:43 UTC by lsaether

closes #14 

Adds an `Asset` variant to distinguish between a `CategoricalOutcome` asset and a `ScalarMarket` asset. Removes the `Shares(Hash)` variant since using hash as identifiers has been deprecated since we moved to using `orml_currencies` instead.

Removes the need to add special fields for the different market types. Instead we use an enum that holds the relevant values per the type of market. Example: `MarketType::Scalar((u128, u128))` holds the `(lower_bound, upper_bound)` for that market. `MarketType::Categorical(u16)` holds the number of categories for that categorical market.

Scalar markets have a different payout logic, so that's being pattern matched inside of the `redeem` function now.

Trying to make the architecture of the pallet more extensible with anticipation for the implementation of the `CombinatorialOutcome` for combinatorial markets, which are right now just stubbed.

Still need to work on tests and finishing the logic.

2021-04-16 19:31 UTC, c410-f3r reviewed
Not very experient with the PM crate but the changes look promising for the upcoming combinatorial markets

2021-04-16 19:31 UTC, c410-f3r commented on primitives/src/asset.rs
> +pub enum Asset<MI> {
Nice. One less type

2021-04-16 19:31 UTC, c410-f3r commented on zrml/prediction-markets/src/market.rs
> +    Scalar((u128, u128)),
Maybe use `RangeInclusive<u128>` or `Range<u128>` (exclusive) as a self-documented structure?

2021-04-19 14:13 UTC, c410-f3r approved these changes

2021-04-19 14:53 UTC, merged

2021-04-19 15:25 UTC, sea212 requested changes
In addition: The project does not compile with `runtime-benchmarks` feature, because the benchmarks for the swaps pallet use the old `Asset` type.

2021-04-19 15:25 UTC, sea212 commented on zrml/prediction-markets/src/lib.rs
> +        #[pallet::weight(10_000)]
Weight is too low. For example, all functions we have so far in the Swaps pallet have a lower weight bound of 50 million (excl. db interactions)

2021-04-19 15:25 UTC, sea212 commented on zrml/prediction-markets/src/tests.rs
>  }
General: create_scalar_market test missing

2021-04-19 15:25 UTC, sea212 commented on node/src/rpc.rs
> -    C::Api: zrml_prediction_markets_rpc::PredictionMarketsRuntimeApi<Block, MarketId, Hash>,
Curious: Why was this removed?

2021-04-19 17:37 UTC, lsaether commented on runtime/src/lib.rs
> +    impl zrml_swaps_runtime_api::SwapsApi<Block, PoolId, AccountId, Balance, MarketId>
It's not longer needed. Originally it was there as more of a convenience method to get the hash of a `Asset::Share(hash)` now that we use asset types based on market index and outcome value, we don't need accesss to a hashing function.

2021-04-19 17:38 UTC, lsaether commented on node/src/rpc.rs
> -    C::Api: zrml_prediction_markets_rpc::PredictionMarketsRuntimeApi<Block, MarketId, Hash>,
answered above

2021-04-19 17:56 UTC, sea212 commented on runtime/src/lib.rs
> +    impl zrml_swaps_runtime_api::SwapsApi<Block, PoolId, AccountId, Balance, MarketId>
That makes sense, thanks